package com.sdlc.pro.txboard.proxy;

import com.sdlc.pro.txboard.delegator.AbstractConnectionDelegator;
import com.sdlc.pro.txboard.listener.TransactionPhaseListener;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public final class ConnectionProxy extends AbstractConnectionDelegator {
    private final TransactionPhaseListener transactionPhaseListener;

    public ConnectionProxy(Connection connection, TransactionPhaseListener transactionPhaseListener) {
        super(connection);
        this.transactionPhaseListener = transactionPhaseListener;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareCall(sql);
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.nativeSQL(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public void close() throws SQLException {
        super.close();
        this.transactionPhaseListener.afterCloseConnection();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql, columnIndexes);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareStatement(sql, columnNames);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        this.transactionPhaseListener.executedQuery(sql);
        return super.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

}
